name: Build and Deploy Angular App to CloudFront
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      BUCKET: angular-demo-testy
      DIST: dist/angular-demo-bitbucket/browser
      REGION: us-east-1
      DIST_ID: E3O2YSZ6R6K3ED

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION }}

    - uses: actions/setup-node@v2
      with:
        node-version: '20.x'
        
    - name: Clear Cache Dependencies
      run: |
        npm cache clean --force

    - name: Install Dependencies
      run: |
        npm --version
        node --version
        npm ci --production
        npm install -g @angular/cli@latest

    - name: Build Static Website
      run: |
        npm install --save-dev @angular-devkit/build-angular --force
        npm run build -- --configuration=production

    - name: Copy files to the production website with the AWS CLI
      run: |
        aws s3 sync --delete ${{ env.DIST }} s3://${{ env.BUCKET }}

    - name: Copy files to the production website with the AWS CLI
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ env.DIST_ID }} \
          --paths "/*"
